var mockData = [
  { id: 'smallfrog732',
    first: 'fletcher',
    last: 'walker',
    photoURL: 'https://randomuser.me/api/portraits/men/64.jpg' },
  { id: 'blackpeacock942',
    first: 'charles',
    last: 'rose',
    photoURL: 'https://randomuser.me/api/portraits/men/52.jpg' },
  { id: 'whiteladybug324',
    first: 'theodore',
    last: 'wang',
    photoURL: 'https://randomuser.me/api/portraits/men/73.jpg' },
  { id: 'whitepanda734',
    first: 'hanne',
    last: 'winkler',
    photoURL: 'https://randomuser.me/api/portraits/women/17.jpg' },
  { id: 'ticklishcat616',
    first: 'falco',
    last: 'carvalho',
    photoURL: 'https://randomuser.me/api/portraits/men/26.jpg' },
  { id: 'greenladybug834',
    first: 'romy',
    last: 'henry',
    photoURL: 'https://randomuser.me/api/portraits/women/83.jpg' },
  { id: 'orangeleopard627',
    first: 'zackary',
    last: 'white',
    photoURL: 'https://randomuser.me/api/portraits/men/68.jpg' },
  { id: 'ticklishwolf937',
    first: 'gilbert',
    last: 'edwards',
    photoURL: 'https://randomuser.me/api/portraits/men/2.jpg' },
  { id: 'silverlion685',
    first: 'bastien',
    last: 'barbier',
    photoURL: 'https://randomuser.me/api/portraits/men/53.jpg' },
  { id: 'bigduck845',
    first: 'magdalena',
    last: 'bravo',
    photoURL: 'https://randomuser.me/api/portraits/women/80.jpg' },
  ]

export default mockData;

